name: test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    defaults:
      run:
        working-directory: circuits

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.2
        with:
          toolchain: 0.10.3

      - name: Run tests
        run: |
          nargo test
